# Generated by Django 3.1.5 on 2021-03-09 15:09

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_remove_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=markdownx.models.MarkdownxField(default='changeme'),
            preserve_default=False,
        ),
    ]
